// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/players.proto

package playerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scorep1       int32                  `protobuf:"varint,1,opt,name=scorep1,proto3" json:"scorep1,omitempty"`
	Scorep2       int32                  `protobuf:"varint,2,opt,name=scorep2,proto3" json:"scorep2,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gamertag      string                 `protobuf:"bytes,4,opt,name=gamertag,proto3" json:"gamertag,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Sponsor       string                 `protobuf:"bytes,6,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResults) Reset() {
	*x = PlayerResults{}
	mi := &file_proto_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResults) ProtoMessage() {}

func (x *PlayerResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResults.ProtoReflect.Descriptor instead.
func (*PlayerResults) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerResults) GetScorep1() int32 {
	if x != nil {
		return x.Scorep1
	}
	return 0
}

func (x *PlayerResults) GetScorep2() int32 {
	if x != nil {
		return x.Scorep2
	}
	return 0
}

func (x *PlayerResults) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerResults) GetGamertag() string {
	if x != nil {
		return x.Gamertag
	}
	return ""
}

func (x *PlayerResults) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PlayerResults) GetSponsor() string {
	if x != nil {
		return x.Sponsor
	}
	return ""
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_proto_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerResults         `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_proto_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerResponse) GetPlayer() *PlayerResults {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_proto_players_proto protoreflect.FileDescriptor

const file_proto_players_proto_rawDesc = "" +
	"\n" +
	"\x13proto/players.proto\x12\n" +
	"players.v1\"\xa1\x01\n" +
	"\rPlayerResults\x12\x18\n" +
	"\ascorep1\x18\x01 \x01(\x05R\ascorep1\x12\x18\n" +
	"\ascorep2\x18\x02 \x01(\x05R\ascorep2\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x1a\n" +
	"\bgamertag\x18\x04 \x01(\tR\bgamertag\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x18\n" +
	"\asponsor\x18\x06 \x01(\tR\asponsor\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x11GetPlayerResponse\x121\n" +
	"\x06player\x18\x01 \x01(\v2\x19.players.v1.PlayerResultsR\x06player2Z\n" +
	"\x0ePlayersService\x12H\n" +
	"\tGetPlayer\x12\x1c.players.v1.GetPlayerRequest\x1a\x1d.players.v1.GetPlayerResponseB%Z#ggstats.com/proto/players;playerspbb\x06proto3"

var (
	file_proto_players_proto_rawDescOnce sync.Once
	file_proto_players_proto_rawDescData []byte
)

func file_proto_players_proto_rawDescGZIP() []byte {
	file_proto_players_proto_rawDescOnce.Do(func() {
		file_proto_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_players_proto_rawDesc), len(file_proto_players_proto_rawDesc)))
	})
	return file_proto_players_proto_rawDescData
}

var file_proto_players_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_players_proto_goTypes = []any{
	(*PlayerResults)(nil),     // 0: players.v1.PlayerResults
	(*GetPlayerRequest)(nil),  // 1: players.v1.GetPlayerRequest
	(*GetPlayerResponse)(nil), // 2: players.v1.GetPlayerResponse
}
var file_proto_players_proto_depIdxs = []int32{
	0, // 0: players.v1.GetPlayerResponse.player:type_name -> players.v1.PlayerResults
	1, // 1: players.v1.PlayersService.GetPlayer:input_type -> players.v1.GetPlayerRequest
	2, // 2: players.v1.PlayersService.GetPlayer:output_type -> players.v1.GetPlayerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_players_proto_init() }
func file_proto_players_proto_init() {
	if File_proto_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_players_proto_rawDesc), len(file_proto_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_players_proto_goTypes,
		DependencyIndexes: file_proto_players_proto_depIdxs,
		MessageInfos:      file_proto_players_proto_msgTypes,
	}.Build()
	File_proto_players_proto = out.File
	file_proto_players_proto_goTypes = nil
	file_proto_players_proto_depIdxs = nil
}
