// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/players.proto

package playerspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Tournament    string                 `protobuf:"bytes,3,opt,name=tournament,proto3" json:"tournament,omitempty"`
	Player1       string                 `protobuf:"bytes,4,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       string                 `protobuf:"bytes,5,opt,name=player2,proto3" json:"player2,omitempty"`
	Scorep1       int32                  `protobuf:"varint,6,opt,name=scorep1,proto3" json:"scorep1,omitempty"`
	Scorep2       int32                  `protobuf:"varint,7,opt,name=scorep2,proto3" json:"scorep2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Match) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *Match) GetTournament() string {
	if x != nil {
		return x.Tournament
	}
	return ""
}

func (x *Match) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *Match) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

func (x *Match) GetScorep1() int32 {
	if x != nil {
		return x.Scorep1
	}
	return 0
}

func (x *Match) GetScorep2() int32 {
	if x != nil {
		return x.Scorep2
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Gamertag      string                 `protobuf:"bytes,2,opt,name=gamertag,proto3" json:"gamertag,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Sponsor       string                 `protobuf:"bytes,4,opt,name=sponsor,proto3" json:"sponsor,omitempty"`
	Matches       []*Match               `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetGamertag() string {
	if x != nil {
		return x.Gamertag
	}
	return ""
}

func (x *Player) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Player) GetSponsor() string {
	if x != nil {
		return x.Sponsor
	}
	return ""
}

func (x *Player) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_proto_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_proto_players_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_players_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_players_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_proto_players_proto protoreflect.FileDescriptor

const file_proto_players_proto_rawDesc = "" +
	"\n" +
	"\x13proto/players.proto\x12\n" +
	"players.v1\"\xcd\x01\n" +
	"\x05Match\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x12\x1e\n" +
	"\n" +
	"tournament\x18\x03 \x01(\tR\n" +
	"tournament\x12\x18\n" +
	"\aplayer1\x18\x04 \x01(\tR\aplayer1\x12\x18\n" +
	"\aplayer2\x18\x05 \x01(\tR\aplayer2\x12\x18\n" +
	"\ascorep1\x18\x06 \x01(\x05R\ascorep1\x12\x18\n" +
	"\ascorep2\x18\a \x01(\x05R\ascorep2\"\x93\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bgamertag\x18\x02 \x01(\tR\bgamertag\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\asponsor\x18\x04 \x01(\tR\asponsor\x12+\n" +
	"\amatches\x18\x05 \x03(\v2\x11.players.v1.MatchR\amatches\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetPlayerResponse\x12*\n" +
	"\x06player\x18\x01 \x01(\v2\x12.players.v1.PlayerR\x06player2Z\n" +
	"\x0ePlayersService\x12H\n" +
	"\tGetPlayer\x12\x1c.players.v1.GetPlayerRequest\x1a\x1d.players.v1.GetPlayerResponseB%Z#ggstats.com/proto/players;playerspbb\x06proto3"

var (
	file_proto_players_proto_rawDescOnce sync.Once
	file_proto_players_proto_rawDescData []byte
)

func file_proto_players_proto_rawDescGZIP() []byte {
	file_proto_players_proto_rawDescOnce.Do(func() {
		file_proto_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_players_proto_rawDesc), len(file_proto_players_proto_rawDesc)))
	})
	return file_proto_players_proto_rawDescData
}

var file_proto_players_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_players_proto_goTypes = []any{
	(*Match)(nil),             // 0: players.v1.Match
	(*Player)(nil),            // 1: players.v1.Player
	(*GetPlayerRequest)(nil),  // 2: players.v1.GetPlayerRequest
	(*GetPlayerResponse)(nil), // 3: players.v1.GetPlayerResponse
}
var file_proto_players_proto_depIdxs = []int32{
	0, // 0: players.v1.Player.matches:type_name -> players.v1.Match
	1, // 1: players.v1.GetPlayerResponse.player:type_name -> players.v1.Player
	2, // 2: players.v1.PlayersService.GetPlayer:input_type -> players.v1.GetPlayerRequest
	3, // 3: players.v1.PlayersService.GetPlayer:output_type -> players.v1.GetPlayerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_players_proto_init() }
func file_proto_players_proto_init() {
	if File_proto_players_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_players_proto_rawDesc), len(file_proto_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_players_proto_goTypes,
		DependencyIndexes: file_proto_players_proto_depIdxs,
		MessageInfos:      file_proto_players_proto_msgTypes,
	}.Build()
	File_proto_players_proto = out.File
	file_proto_players_proto_goTypes = nil
	file_proto_players_proto_depIdxs = nil
}
