FROM golang:1.24.6 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/matches/cmd/grpc
RUN go build -o /app/matches-grpc .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/matches-grpc .

EXPOSE 50052
CMD ["./matches-grpc"]