FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/metadata/cmd/main
RUN go build -o /app/metadata/metadata .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/metadata/metadata .

EXPOSE 8081
CMD ["./metadata"]