FROM golang:1.24.6 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/players/cmd/grpc
RUN go build -o /app/players-grpc .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/players-grpc .

EXPOSE 50053
CMD ["./players-grpc"]
