FROM golang:1.25 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy

WORKDIR /app/matches/cmd/main
RUN go build -o /app/matches/matches .

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/matches/matches .

EXPOSE 8082
CMD ["./matches"]