apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
  namespace: ggstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
      - name: metadata
        image: ggstats-metadata:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: metadata
  namespace: ggstats
spec:
  type: ClusterIP
  selector:
    app: metadata
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
