// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/matches.proto

package matchespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	Tournament    string                 `protobuf:"bytes,3,opt,name=tournament,proto3" json:"tournament,omitempty"`
	Player1       string                 `protobuf:"bytes,4,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2       string                 `protobuf:"bytes,5,opt,name=player2,proto3" json:"player2,omitempty"`
	Scorep1       int32                  `protobuf:"varint,6,opt,name=scorep1,proto3" json:"scorep1,omitempty"`
	Scorep2       int32                  `protobuf:"varint,7,opt,name=scorep2,proto3" json:"scorep2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_matches_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matches_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_matches_proto_rawDescGZIP(), []int{0}
}

func (x *Match) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Match) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *Match) GetTournament() string {
	if x != nil {
		return x.Tournament
	}
	return ""
}

func (x *Match) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *Match) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

func (x *Match) GetScorep1() int32 {
	if x != nil {
		return x.Scorep1
	}
	return 0
}

func (x *Match) GetScorep2() int32 {
	if x != nil {
		return x.Scorep2
	}
	return 0
}

type GetMatchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	RecordType    string                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesRequest) Reset() {
	*x = GetMatchesRequest{}
	mi := &file_proto_matches_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesRequest) ProtoMessage() {}

func (x *GetMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matches_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesRequest.ProtoReflect.Descriptor instead.
func (*GetMatchesRequest) Descriptor() ([]byte, []int) {
	return file_proto_matches_proto_rawDescGZIP(), []int{1}
}

func (x *GetMatchesRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *GetMatchesRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

type GetMatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchesResponse) Reset() {
	*x = GetMatchesResponse{}
	mi := &file_proto_matches_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchesResponse) ProtoMessage() {}

func (x *GetMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matches_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchesResponse.ProtoReflect.Descriptor instead.
func (*GetMatchesResponse) Descriptor() ([]byte, []int) {
	return file_proto_matches_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchesResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type PutMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         *Match                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutMatchRequest) Reset() {
	*x = PutMatchRequest{}
	mi := &file_proto_matches_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMatchRequest) ProtoMessage() {}

func (x *PutMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matches_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMatchRequest.ProtoReflect.Descriptor instead.
func (*PutMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_matches_proto_rawDescGZIP(), []int{3}
}

func (x *PutMatchRequest) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type PutMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutMatchResponse) Reset() {
	*x = PutMatchResponse{}
	mi := &file_proto_matches_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMatchResponse) ProtoMessage() {}

func (x *PutMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matches_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMatchResponse.ProtoReflect.Descriptor instead.
func (*PutMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_matches_proto_rawDescGZIP(), []int{4}
}

var File_proto_matches_proto protoreflect.FileDescriptor

const file_proto_matches_proto_rawDesc = "" +
	"\n" +
	"\x13proto/matches.proto\x12\vmetadata.v1\"\xcd\x01\n" +
	"\x05Match\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\x12\x1e\n" +
	"\n" +
	"tournament\x18\x03 \x01(\tR\n" +
	"tournament\x12\x18\n" +
	"\aplayer1\x18\x04 \x01(\tR\aplayer1\x12\x18\n" +
	"\aplayer2\x18\x05 \x01(\tR\aplayer2\x12\x18\n" +
	"\ascorep1\x18\x06 \x01(\x05R\ascorep1\x12\x18\n" +
	"\ascorep2\x18\a \x01(\x05R\ascorep2\"Q\n" +
	"\x11GetMatchesRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1f\n" +
	"\vrecord_type\x18\x02 \x01(\tR\n" +
	"recordType\"B\n" +
	"\x12GetMatchesResponse\x12,\n" +
	"\amatches\x18\x01 \x03(\v2\x12.metadata.v1.MatchR\amatches\";\n" +
	"\x0fPutMatchRequest\x12(\n" +
	"\x05match\x18\x01 \x01(\v2\x12.metadata.v1.MatchR\x05match\"\x12\n" +
	"\x10PutMatchResponse2\xa8\x01\n" +
	"\x0eMatchesService\x12M\n" +
	"\n" +
	"GetMatches\x12\x1e.metadata.v1.GetMatchesRequest\x1a\x1f.metadata.v1.GetMatchesResponse\x12G\n" +
	"\bPutMatch\x12\x1c.metadata.v1.PutMatchRequest\x1a\x1d.metadata.v1.PutMatchResponseB%Z#ggstats.com/proto/matches;matchespbb\x06proto3"

var (
	file_proto_matches_proto_rawDescOnce sync.Once
	file_proto_matches_proto_rawDescData []byte
)

func file_proto_matches_proto_rawDescGZIP() []byte {
	file_proto_matches_proto_rawDescOnce.Do(func() {
		file_proto_matches_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matches_proto_rawDesc), len(file_proto_matches_proto_rawDesc)))
	})
	return file_proto_matches_proto_rawDescData
}

var file_proto_matches_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_matches_proto_goTypes = []any{
	(*Match)(nil),              // 0: metadata.v1.Match
	(*GetMatchesRequest)(nil),  // 1: metadata.v1.GetMatchesRequest
	(*GetMatchesResponse)(nil), // 2: metadata.v1.GetMatchesResponse
	(*PutMatchRequest)(nil),    // 3: metadata.v1.PutMatchRequest
	(*PutMatchResponse)(nil),   // 4: metadata.v1.PutMatchResponse
}
var file_proto_matches_proto_depIdxs = []int32{
	0, // 0: metadata.v1.GetMatchesResponse.matches:type_name -> metadata.v1.Match
	0, // 1: metadata.v1.PutMatchRequest.match:type_name -> metadata.v1.Match
	1, // 2: metadata.v1.MatchesService.GetMatches:input_type -> metadata.v1.GetMatchesRequest
	3, // 3: metadata.v1.MatchesService.PutMatch:input_type -> metadata.v1.PutMatchRequest
	2, // 4: metadata.v1.MatchesService.GetMatches:output_type -> metadata.v1.GetMatchesResponse
	4, // 5: metadata.v1.MatchesService.PutMatch:output_type -> metadata.v1.PutMatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_matches_proto_init() }
func file_proto_matches_proto_init() {
	if File_proto_matches_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matches_proto_rawDesc), len(file_proto_matches_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matches_proto_goTypes,
		DependencyIndexes: file_proto_matches_proto_depIdxs,
		MessageInfos:      file_proto_matches_proto_msgTypes,
	}.Build()
	File_proto_matches_proto = out.File
	file_proto_matches_proto_goTypes = nil
	file_proto_matches_proto_depIdxs = nil
}
